os: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - git submodule update --init --recursive
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%